### ISSUE TITLE
Apply the pre-trained RepUX-Net weights.

### ISSUE THREAD

**Issue by Luoxd1996** [MASILab/RepUX-Net#1]
Dear, Dr. Ho Hin Lee: 
I am working on the topic of abdominal organ segmentation. I am planning to release a real clinical and human-labeled dataset to evaluate the robustness of recent methods. I know your works (3DUXNET and REPUXNET) are the SOTA methods, so I want to evaluate your pre-trained model (on AMOS) on our collected dataset. We want to know that is there any plans to release your pre-trained models. We will release the dataset and benchmark one month later, which is a heavy extension from our previous WORD (which collected more challenging and corner cases). We will cite your work, which has boosted our project deeply.
Best,
Xiangde Luo.

**Comment by leeh43** [comment]
Hi Xiangde, thank you for your interest towards our work. I will definitely release my pretrained model and sorry for the delay (Because I just graduated and onboarded with my job). I will try my best to put the pretrained model link within this week and give you a notification here!

**Comment by Luoxd1996** [comment]
Hi, Lee:
Thank you for your quick response. Congratulations on your graduation! I will look forward to staying updated on your series of works.
Best,
Xiangde Luo.

**Comment by leeh43** [comment]
Hi Xiangde, I have push a google drive link for the AMOS pretrained model in the GitHub Readme. Feel free to use it for inference and ask for help if there is additional problems or inquries.

Best,
Peter

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
