### ISSUE TITLE
How to train RepOptimizers as a medical segmentation model?

### ISSUE THREAD

**Issue by landonmax0** [MASILab/RepUX-Net#3]
Thank you for providing this innovative segmentation model. 

I noticed that you compared RepOptimizers in your article, and I would like to know how that was done? How to use RepOptimizers as a segmentation model to segment CT image datasets? What code do I need to modify? Because the original project does not seem to provide such functionality.

I would greatly appreciate it if you could reply to me. Wishing you a smooth work experience.

![image](https://github.com/user-attachments/assets/110e9b09-4acc-4002-ab86-4ecea1c9f5d5)

**Comment by BennettLandman** [comment]
Please contact the corresponding author.
